### ISSUE TITLE
[Suggestion] Physics 

### ISSUE THREAD

**Issue by Lucas-101** [RandomGamingDev/Wireframe#1]
Physics engine?

**Comment by RandomGamingDev** [comment]
For this project I only wanted to include the basics that you need to make your game, to keep the engine simple and I wanted to avoid stuff that could affect the feeling of your game. Putting a default physics engine would encourage the user of the library to simply choose that default option, which might or might not be the best choice, and would go against the simplicity and other attributes of this engine. Plus, I don't have a custom physics engine right now, so I would probably have to use a 3rd party engine, which you might as well import yourself anyways if you have to. Maybe I'll add a physics engine in the future, but right now I don't think that that would be the best idea. Also, just to let you and whoever are reading this know, I don't oppose change to the engine, I actively encourage it, but it's just that I don't feel like it's the best choice for the engine.

**Comment by Lucas-101** [comment]
Makes sense
